### ISSUE TITLE
v3 Beta (Vue 3)

### ISSUE THREAD

**Issue by gilbitron** [gilbitron/laravel-vue-pagination#124]
I've just released a v3 beta of this plugin which is a re-write for Vue 3. Please see the [latest releases](https://github.com/gilbitron/laravel-vue-pagination/releases) and install using `laravel-vue-pagination@next`. The code and REAMDE are available in the [v3 branch](https://github.com/gilbitron/laravel-vue-pagination/tree/v3). 

I'd appreciate it if you could help test the beta and share any feedback you have in this issue.

**Comment by barryp** [comment]
Nice, I swapped out my branch for this and it worked without any problems.

**Comment by mfutselaar** [comment]
The limit property seems to be ignored, no matter what value i add to it, all pages still get rendered.

`<pagination :data="laravelData" @pagination-change-page="getData" limit="15" />`

results in

![image](https://user-images.githubusercontent.com/6617049/154024261-8c864bd3-4fdb-4de3-96ac-35eba8a66a51.png)

**Comment by gilbitron** [comment]
@mfutselaar You should be passing the limit as a number, not a string `:limit="15"` (note the ":").

**Comment by gilbitron** [comment]
I've just published v3.0.0 making Vue 3 support the default for this package https://github.com/gilbitron/laravel-vue-pagination/releases/tag/3.0.0

**Comment by ankurk91** [comment]
Not working for me in Vue 3.2

```bash
laravel-vue-pagination.es.js:226 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'computed')
    at eval (laravel-vue-pagination.es.js:226:1)
    at renderFnWithContext (vue.esm-bundler.js:2976:1)
    at Object.get (vue.esm-bundler.js:5325:1)
    at Proxy.render (laravel-vue-pagination.es.js:116:1)
    at Proxy.compatRender (vue.esm-bundler.js:5132:1)
    at renderComponentRoot (vue.esm-bundler.js:3023:1)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.esm-bundler.js:8930:1)
    at ReactiveEffect.run (vue.esm-bundler.js:611:1)
    at instance.update (vue.esm-bundler.js:9056:1)
    at setupRenderEffect (vue.esm-bundler.js:9070:1)
```
